### ISSUE TITLE
Reference Number / Payment Message at Checkout

### ISSUE THREAD

**Issue by magedmoh94** [ash2osh/atfawry_woocomerce#2]
1. The Reference number doesn't show in the order email & in the thank you page after the checkout.

2. Payment Message that appears under the Payment Name in the checkout page doesn't show up.

**Comment by ash2osh** [comment]
any pull request is welcomed

**Comment by magedmoh94** [comment]
I hope i can help in that but i can't, my store is stopped working & i hope i can have a contact with you. Everything is stopped .. check your facebook inbox
