### ISSUE TITLE
Cancel Unpaid On Hold Schedule Order doesn't work

### ISSUE THREAD

**Issue by magedmoh94** [ash2osh/atfawry_woocomerce#4]
I need make the orders to be canceled after 4 hours if the customer didn't pay at fawry after 4 hours the order status changes from on-hold to canceled.

Also i don't know if they are canceled from wordpress system cron event or wordpress receive a callback for the cancellation to change the order status from on-hold to canceled as it happens when the order paid which make it change from on-hold to completed

**Suggestion:** for sure it will be better if the order is canceled by a callback from fawry as it happens for the completed status

**Comment by ash2osh** [comment]
merged your pull request
